blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/nytsdayo/cub3D/discussions
    about: ä¸€èˆ¬çš„ãªè­°è«–ã‚„è³ªå•ã¯ã“ã¡ã‚‰ã§ / General discussions and questions
